# Generated by Django 4.2.11 on 2026-07-11 20:28

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('token', models.CharField(default=uuid.uuid4, max_length=128, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('pending_full_index', models.BooleanField(default=False)),
                ('pending_restart', models.BooleanField(default=False)),
                ('pending_update', models.BooleanField(default=False)),
                ('last_restart', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('site_title', models.CharField(default='Astra File Monitor', max_length=100, verbose_name='Название сайта')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TriggerWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('substring_match', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_owner', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('ack', 'Подтверждён'), ('resolved', 'Решён')], default='new', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agent')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trigger_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.triggerword')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_directories', models.TextField(default='/home', help_text='Список директорий через запятую')),
                ('exclude_patterns', models.TextField(blank=True, help_text='Шаблоны исключений (regex), по одному на строку')),
                ('max_file_size_mb', models.IntegerField(default=50)),
                ('allowed_extensions', models.TextField(default='.txt,.log,.md,.csv,.json,.xml,.yaml,.yml,.ini,.cfg,.conf,.html,.odt,.docx,.rtf,.pdf')),
                ('scan_interval_minutes', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_mtime', models.DateTimeField()),
                ('content_text', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'file_path'], name='core_filere_agent_i_5c3bb1_idx'), models.Index(fields=['file_name'], name='core_filere_file_na_132226_idx')],
                'unique_together': {('agent', 'file_path')},
            },
        ),
    ]
